// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPDFT-tVLhYFF0DacTfYb-7TY3A7oTzk',
    appId: '1:379407539467:web:54378b286248d1ee3b160e',
    messagingSenderId: '379407539467',
    projectId: 'fir-sample-25f6e',
    authDomain: 'fir-sample-25f6e.firebaseapp.com',
    storageBucket: 'fir-sample-25f6e.appspot.com',
    measurementId: 'G-1HJW7FW3GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApLPA_R0Tpt4zNVqr5ppVWyA_u_WW2IZw',
    appId: '1:379407539467:android:3de94d395f3bc76d3b160e',
    messagingSenderId: '379407539467',
    projectId: 'fir-sample-25f6e',
    storageBucket: 'fir-sample-25f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_NPlhRpdqOXvQmZ1XDsTytQ3Eb_9cpb4',
    appId: '1:379407539467:ios:ea09fc543569b2c93b160e',
    messagingSenderId: '379407539467',
    projectId: 'fir-sample-25f6e',
    storageBucket: 'fir-sample-25f6e.appspot.com',
    iosBundleId: 'com.example.mainExamTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_NPlhRpdqOXvQmZ1XDsTytQ3Eb_9cpb4',
    appId: '1:379407539467:ios:ea09fc543569b2c93b160e',
    messagingSenderId: '379407539467',
    projectId: 'fir-sample-25f6e',
    storageBucket: 'fir-sample-25f6e.appspot.com',
    iosBundleId: 'com.example.mainExamTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDndE0TI-Eg6fYETEY65VyHY9HfMKaikzw',
    appId: '1:379407539467:web:5d728d56a5fe272b3b160e',
    messagingSenderId: '379407539467',
    projectId: 'fir-sample-25f6e',
    authDomain: 'fir-sample-25f6e.firebaseapp.com',
    storageBucket: 'fir-sample-25f6e.appspot.com',
    measurementId: 'G-54M2YGL529',
  );
}
